const MyTeamTestData = [
  {
    id: 1,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction:
      "한줄 가나 가나 가나 가나 가나 가나 가나 가나 가나 가나 가나 가나 가나 가나",
  },
  {
    id: 2,
    projectName: "알파",
    teamName: "이음",
    region: "서울/경기",
    recruitment: false,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 3,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 4,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 5,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 6,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 7,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 8,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 9,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 10,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 11,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 12,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 13,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 14,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 15,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 16,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 17,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 18,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    id: 19,
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
];

export default MyTeamTestData;
