const teamTestData = [
  {
    id: 1,
    projectName: "Awesome Project",
    recruitmentStatus: true,
    postedTime: "2024-03-16T12:00:00Z",
    teamName: "Dream Team",
    location: "서울",
    projectDescription:
      "이 프로젝트는 놀라운 기술을 개발하는 것을 목표로 합니다.",
    category1: "웹 개발",
    category2: "인공지능",
    like: false,
  },
  {
    id: 2,
    projectName: "Cool Project",
    recruitmentStatus: false,
    postedTime: "2024-03-15T09:30:00Z",
    teamName: "Tech Savvy",
    location: "경기",
    projectDescription:
      "최신 기술을 활용하여 혁신적인 솔루션을 개발하는 프로젝트입니다.",
    category1: "앱 개발",
    category2: "데이터 분석",
    like: true,
  },
  {
    id: 3,
    projectName: "Innovative Project",
    recruitmentStatus: true,
    postedTime: "2024-03-14T15:45:00Z",
    teamName: "Code Masters",
    location: "부산",
    projectDescription: "창의적인 소프트웨어 솔루션을 개발하는 프로젝트입니다.",
    category1: "게임 개발",
    category2: "블록체인",
    like: true,
  },
  {
    id: 4,
    projectName: "Exciting Project",
    recruitmentStatus: true,
    postedTime: "2024-03-17T10:00:00Z",
    teamName: "Innovators",
    location: "서울",
    projectDescription:
      "흥미로운 프로젝트를 개발하여 혁신을 이끌어내는 팀입니다.",
    category1: "데이터 사이언스",
    category2: "클라우드 컴퓨팅",
    like: true,
  },
  {
    id: 5,
    projectName: "Future Project",
    recruitmentStatus: false,
    postedTime: "2024-03-18T14:30:00Z",
    teamName: "Visionaries",
    location: "경기",
    projectDescription: "미래를 대비한 혁신적인 프로젝트를 수행하는 팀입니다.",
    category1: "로봇공학",
    category2: "인터넷 of Things (IoT)",
    like: false,
  },
  {
    id: 6,
    projectName: "Tech Project",
    recruitmentStatus: true,
    postedTime: "2024-03-19T09:45:00Z",
    teamName: "Tech Wizards",
    location: "부산",
    projectDescription:
      "기술적 도전에 재미를 느끼며 혁신적인 솔루션을 개발하는 팀입니다.",
    category1: "소프트웨어 개발",
    category2: "머신 러닝",
    like: false,
  },
];

export default teamTestData;
