const MyTeamTestData = [
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction:
      "한줄 가나 가나 가나 가나 가나 가나 가나 가나 가나 가나 가나 가나 가나 가나",
  },
  {
    projectName: "알파",
    teamName: "이음",
    region: "서울/경기",
    recruitment: false,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
  {
    projectName: "프로젝트이름",
    teamName: "팀이름",
    region: "지역",
    recruitment: true,
    recruitmentTime: "1시간",
    introduction: "한줄 소개",
  },
];

export default MyTeamTestData;
