const teamTestData3 = [
  {
    id: 1,
    projectName: "Awesome Project",
    recruitmentStatus: true,
    postedTime: "2024-03-16T12:00:00Z",
    teamName: "Dream Team",
    location: "서울",
    projectDescription:
      "이 프로젝트는 놀라운 기술을 개발하는 것을 목표로 합니다.",
    category1: "웹 개발",
    category2: "인공지능",
    like: false,
  },
  {
    id: 2,
    projectName: "Cool Project",
    recruitmentStatus: false,
    postedTime: "2024-03-15T09:30:00Z",
    teamName: "Tech Savvy",
    location: "경기",
    projectDescription:
      "최신 기술을 활용하여 혁신적인 솔루션을 개발하는 프로젝트입니다.",
    category1: "앱 개발",
    category2: "데이터 분석",
    like: true,
  },
  {
    id: 3,
    projectName: "Innovative Project",
    recruitmentStatus: true,
    postedTime: "2024-03-14T15:45:00Z",
    teamName: "Code Masters",
    location: "부산",
    projectDescription: "창의적인 소프트웨어 솔루션을 개발하는 프로젝트입니다.",
    category1: "게임 개발",
    category2: "블록체인",
    like: true,
  },
  // 더미 데이터 추가
  {
    id: 4,
    projectName: "Exciting Project",
    recruitmentStatus: true,
    postedTime: "2024-03-17T10:20:00Z",
    teamName: "Innovators",
    location: "서울",
    projectDescription: "흥미로운 기술을 연구하고 개발하는 프로젝트입니다.",
    category1: "로봇 공학",
    category2: "사물 인터넷",
    like: false,
  },
  {
    id: 5,
    projectName: "Future Tech Project",
    recruitmentStatus: false,
    postedTime: "2024-03-18T14:00:00Z",
    teamName: "Digital Pioneers",
    location: "경기",
    projectDescription:
      "미래 기술에 대한 연구 및 개발을 목표로 하는 프로젝트입니다.",
    category1: "가상 현실",
    category2: "로봇 공학",
    like: true,
  },
  {
    id: 6,
    projectName: "Revolutionary Project",
    recruitmentStatus: true,
    postedTime: "2024-03-19T08:45:00Z",
    teamName: "Tech Innovate",
    location: "부산",
    projectDescription:
      "혁신적인 기술을 활용하여 사회적 문제를 해결하는 프로젝트입니다.",
    category1: "인공지능",
    category2: "사회 문제 해결",
    like: true,
  },
  {
    id: 7,
    projectName: "Next Gen Project",
    recruitmentStatus: true,
    postedTime: "2024-03-20T11:30:00Z",
    teamName: "Visionaries",
    location: "서울",
    projectDescription: "다음 세대 기술을 개발하는 프로젝트입니다.",
    category1: "바이오 테크놀로지",
    category2: "DNA 염기서열 분석",
    like: false,
  },
  {
    id: 8,
    projectName: "Smart Solutions",
    recruitmentStatus: false,
    postedTime: "2024-03-21T13:20:00Z",
    teamName: "Tech Wizards",
    location: "경기",
    projectDescription:
      "스마트한 솔루션을 개발하여 일상적인 문제를 해결하는 프로젝트입니다.",
    category1: "빅데이터",
    category2: "사물 인터넷",
    like: true,
  },
  {
    id: 9,
    projectName: "Creative Project",
    recruitmentStatus: true,
    postedTime: "2024-03-22T09:15:00Z",
    teamName: "Innovation Lab",
    location: "부산",
    projectDescription:
      "창의적인 아이디어를 기반으로 기술을 개발하는 프로젝트입니다.",
    category1: "가상 현실",
    category2: "블록체인",
    like: true,
  },
  {
    id: 10,
    projectName: "Tech for Good Project",
    recruitmentStatus: true,
    postedTime: "2024-03-23T15:10:00Z",
    teamName: "Future Thinkers",
    location: "서울",
    projectDescription:
      "기술을 활용하여 사회에 긍정적인 영향을 미치는 프로젝트입니다.",
    category1: "사회 문제 해결",
    category2: "인공지능",
    like: false,
  },
  {
    id: 11,
    projectName: "Innovative Solutions",
    recruitmentStatus: false,
    postedTime: "2024-03-24T12:50:00Z",
    teamName: "Tech Solutions",
    location: "경기",
    projectDescription:
      "혁신적인 솔루션을 개발하여 산업에 기여하는 프로젝트입니다.",
    category1: "데이터 분석",
    category2: "사물 인터넷",
    like: true,
  },
  {
    id: 12,
    projectName: "Future Innovations",
    recruitmentStatus: true,
    postedTime: "2024-03-25T14:30:00Z",
    teamName: "Innovation Hub",
    location: "부산",
    projectDescription:
      "미래를 위한 혁신적인 기술을 연구 및 개발하는 프로젝트입니다.",
    category1: "로봇 공학",
    category2: "가상 현실",
    like: true,
  },
  {
    id: 13,
    projectName: "Cutting-edge Tech",
    recruitmentStatus: true,
    postedTime: "2024-03-26T08:40:00Z",
    teamName: "Tech Explorers",
    location: "서울",
    projectDescription: "선도적인 기술을 탐구하고 개발하는 프로젝트입니다.",
    category1: "인공지능",
    category2: "바이오 테크놀로지",
    like: false,
  },
  {
    id: 14,
    projectName: "Digital Innovation",
    recruitmentStatus: false,
    postedTime: "2024-03-27T10:15:00Z",
    teamName: "Innovation Architects",
    location: "경기",
    projectDescription:
      "디지털 혁신을 위한 연구 및 개발을 수행하는 프로젝트입니다.",
    category1: "데이터 분석",
    category2: "사물 인터넷",
    like: true,
  },
  {
    id: 15,
    projectName: "AI Revolution Project",
    recruitmentStatus: true,
    postedTime: "2024-03-28T13:00:00Z",
    teamName: "Tech Evolution",
    location: "부산",
    projectDescription: "인공지능 혁명을 주도하는 프로젝트입니다.",
    category1: "인공지능",
    category2: "로봇 공학",
    like: true,
  },
];

export default teamTestData3;
